name: CI
on:
  push:
    branches: [master]
  pull_request: {}
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [26, 27, "master"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CI
        env:
          VERSION: ${{ matrix.emacs_version }}
        run: >-
          make docker CMD="make -k link lint"
